### ISSUE TITLE
Does not use second name

### ISSUE THREAD

**Issue by acjbizar** [brunocarvalhodearaujo/react-initial#1]
When the `name` is fed a first and second (last) name, and the `charCount` is set to 2, the first two letters of the first name are used. That is not what one normally considers to be the initials.

**Comment by acjbizar** [comment]
(This can of course be worked around by passing something like `{firstName.charAt(0) + lastName.charAt(0)}` to `name`, but then you’re actually no longer passing a name. It would be nice if the component handles this internally.)

**Comment by varevarao** [comment]
Solved in #8
